# Generated by Django 5.1.5 on 2025-03-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='movie/video/movies/trailers/'),
        ),
    ]
